"""добавил cascade удаление в bookingsOrm

Revision ID: 25418cbcbc16
Revises: 134f1c08d91c
Create Date: 2026-03-17 15:03:29.138808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "25418cbcbc16"
down_revision: Union[str, Sequence[str], None] = "134f1c08d91c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("bookings_user_id_fkey"), "bookings", type_="foreignkey")
    op.drop_constraint(op.f("bookings_room_id_fkey"), "bookings", type_="foreignkey")
    op.create_foreign_key(
        None, "bookings", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "bookings", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookings_room_id_fkey"), "bookings", "rooms", ["room_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("bookings_user_id_fkey"), "bookings", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
