"""Поменя тип пароля

Revision ID: 21db2822878f
Revises: f2486dd29dae
Create Date: 2026-06-17 11:39:59.181496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "21db2822878f"
down_revision: Union[str, Sequence[str], None] = "f2486dd29dae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="hashed_password::bytea"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
        postgresql_using="encode(hashed_password, 'escape')"
    )
    # ### end Alembic commands ###
