"""добавил поля об оплате

Revision ID: c03dd9b4fa4d
Revises: 21db2822878f
Create Date: 2026-06-18 18:03:26.728566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c03dd9b4fa4d"
down_revision: Union[str, Sequence[str], None] = "21db2822878f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "is_paid", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("bookings", sa.Column("paid_date", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "paid_date")
    op.drop_column("bookings", "is_paid")
    # ### end Alembic commands ###
