"""добавил даты

Revision ID: eb6771b55c67
Revises: c03dd9b4fa4d
Create Date: 2026-06-19 09:02:21.517393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eb6771b55c67"
down_revision: Union[str, Sequence[str], None] = "c03dd9b4fa4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms_facilities",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms_facilities",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Bishkek', now())"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("rooms_facilities", "updated_at")
    op.drop_column("rooms_facilities", "created_at")
    op.drop_column("rooms", "updated_at")
    op.drop_column("rooms", "created_at")
    op.drop_column("hotels", "updated_at")
    op.drop_column("hotels", "created_at")
    op.drop_column("bookings", "updated_at")
    op.drop_column("bookings", "created_at")
    # ### end Alembic commands ###
