"""добавил статус брони

Revision ID: d701a76a717c
Revises: eb6771b55c67
Create Date: 2026-06-19 11:48:53.597387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d701a76a717c"
down_revision: Union[str, Sequence[str], None] = "eb6771b55c67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCESS",
                "CANCELED",
                name="status",
                native_enum=False,
                length=20,
            ),
            server_default="PENDING",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "status")
    # ### end Alembic commands ###
