"""добавил роли к юзерам

Revision ID: a01b25da97eb
Revises: 0ad1d14acd4b
Create Date: 2026-06-22 16:54:26.209227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a01b25da97eb"
down_revision: Union[str, Sequence[str], None] = "0ad1d14acd4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userstatus_enum = sa.Enum("ADMIN", "MANAGER", "USER", name="userstatus")

    bind = op.get_bind()
    userstatus_enum.create(bind, checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.Enum("ADMIN", "MANAGER", "USER", name="userstatus"),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    # ### end Alembic commands ###
