"""Добавил проверки в модели

Revision ID: 0c9c0d782e5c
Revises: a01b25da97eb
Create Date: 2026-06-23 18:11:55.855543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0c9c0d782e5c"
down_revision: Union[str, Sequence[str], None] = "a01b25da97eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_title_location_uc", "hotels", ["title", "location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_title_location_uc", "hotels", type_="unique")
    # ### end Alembic commands ###
